name = "LevyProcesses"
uuid = "c545b0d6-e5a5-4c08-a7b6-06dfe4503686"
version = "0.1.0"
authors = ["THargreaves <tim.hargreaves@icloud.com>"]

[deps]
AcceleratedKernels = "6a4ca0a5-0e36-4168-a932-d9be78d558f1"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StableDistributions = "3756410d-ab6e-41a2-9897-9aa267a7ef31"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
AcceleratedKernels = "0.3.0"
HypergeometricFunctions = "0.3.28"
HypothesisTests = "0.11.5"
QuadGK = "2.11.2"
Random = "1.11.0"
Roots = "2.2.10"
SpecialFunctions = "2.6.1"
StaticArrays = "1.9.13"
Statistics = "1.11.1"
Test = "1.11.0"
TestItemRunner = "1.1.0"
TestItems = "1.0.0"

[extras]
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[targets]
test = ["HypothesisTests", "Test", "TestItems", "TestItemRunner"]
